<?php
/**
 * DefaultApiTest
 * PHP version 5.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Mautic Trello API.
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi\lib;

use MauticPlugin\Idea2TrelloBundle\Openapi\lib\ApiException;
use MauticPlugin\Idea2TrelloBundle\Openapi\lib\Configuration;
use MauticPlugin\Idea2TrelloBundle\Openapi\lib\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addCard.
     *
     * .
     */
    public function testAddCard()
    {
    }

    /**
     * Test case for getBoards.
     *
     * .
     */
    public function testGetBoards()
    {
    }

    /**
     * Test case for getLists.
     *
     * .
     */
    public function testGetLists()
    {
    }
}
