<?php
/**
 * CardAllOfTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Idea2 Trello API.
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi;

use PHPUnit\Framework\TestCase;

/**
 * CardAllOfTest Class Doc Comment.
 *
 * @category    Class
 * @description CardAllOf
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class CardAllOfTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardAllOf".
     */
    public function testCardAllOf()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "labels".
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "url".
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "date_last_activity".
     */
    public function testPropertyDateLastActivity()
    {
    }

    /**
     * Test attribute "due".
     */
    public function testPropertyDue()
    {
    }

    /**
     * Test attribute "id_members".
     */
    public function testPropertyIdMembers()
    {
    }

    /**
     * Test attribute "attachments".
     */
    public function testPropertyAttachments()
    {
    }
}
