<?php
/**
 * NewCardTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Idea2 Trello API.
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi;

use PHPUnit\Framework\TestCase;

/**
 * NewCardTest Class Doc Comment.
 *
 * @category    Class
 * @description NewCard
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class NewCardTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewCard".
     */
    public function testNewCard()
    {
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "id_list".
     */
    public function testPropertyIdList()
    {
    }

    /**
     * Test attribute "desc".
     */
    public function testPropertyDesc()
    {
    }

    /**
     * Test attribute "pos".
     */
    public function testPropertyPos()
    {
    }

    /**
     * Test attribute "due".
     */
    public function testPropertyDue()
    {
    }

    /**
     * Test attribute "url_source".
     */
    public function testPropertyUrlSource()
    {
    }

    /**
     * Test attribute "keep_from_source".
     */
    public function testPropertyKeepFromSource()
    {
    }
}
