<?php
/**
 * TrelloListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MauticPlugin\Idea2TrelloBundle\Openapi\lib
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mautic Trello API
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi\lib;

use PHPUnit\Framework\TestCase;

/**
 * TrelloListTest Class Doc Comment
 *
 * @category    Class
 * @description TrelloList
 * @package     MauticPlugin\Idea2TrelloBundle\Openapi\lib
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrelloListTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TrelloList"
     */
    public function testTrelloList()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "pos"
     */
    public function testPropertyPos()
    {
    }
}
