<?php

declare(strict_types=1);
/**
 * @copyright   2020 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @see        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace MauticPlugin\Idea2TrelloBundle\Service;

use Exception;
use GuzzleHttp\Client as HttpClient;
use Mautic\CoreBundle\Helper\CoreParametersHelper;
use Mautic\PluginBundle\Helper\IntegrationHelper;
use MauticPlugin\Idea2TrelloBundle\Integration\TrelloIntegration;
use MauticPlugin\Idea2TrelloBundle\Openapi\lib\Api\DefaultApi;
use MauticPlugin\Idea2TrelloBundle\Openapi\lib\Configuration;
use MauticPlugin\Idea2TrelloBundle\Openapi\lib\Model\Card;
use Monolog\Logger;

/**
 * Provide the auto generated Trello API to the Idea2TrelloBundle.
 */
class TrelloApiService
{
    /**
     * @var bool|TrelloIntegration
     */
    protected $integration;

    /**
     * @var CoreParametersHelper
     */
    protected $coreParametersHelper;

    /**
     * @var Logger
     */
    protected $logger;

    /**
     * Setup Service.
     */
    public function __construct(IntegrationHelper $integrationHelper, CoreParametersHelper $coreParametersHelper, Logger $logger)
    {
        $this->integration = $integrationHelper->getIntegrationObject('Trello');
        $this->coreParametersHelper = $coreParametersHelper;
        $this->logger = $logger;
    }

    /**
     * Return the Api to Trello. Autogenerated, based on OpenAPI.
     *
     * @return \Openapi\lib\Api\DefaultApi $api
     */
    public function getApi(): DefaultApi
    {
        // setup auth
        $auth = $this->getAuthParams();
        $config = Configuration::getDefaultConfiguration()->setApiKey('key', $auth['key']);
        $config = Configuration::getDefaultConfiguration()->setApiKey('token', $auth['token']);

        return new DefaultApi(
            new HttpClient(),
            $config
        );
    }

    /**
     * Get the users favourite board from Settings.
     *
     * @return string
     */
    public function getFavouriteBoard()
    {
        return $this->coreParametersHelper->get('favorite_board', '');
    }

    /**
     * Get all the lists on the Trello board.
     *
     * @param int $boardId
     */
    public function getListsOnBoard(int $boardId = null): array
    {
        $api = $this->getApi();

        if (empty($boardId)) {
            $boardId = $this->getFavouriteBoard();
            if (empty($boardId)) {
                $this->logger->warning('no board configured');

                return [];
            }
        }

        try {
            return $api->getLists($boardId);
        } catch (Exception $e) {
            $this->logger->warning('Exception when calling DefaultApi->getLists: ', [$e->getMessage()]);

            return [];
        }
    }

    /**
     * Get the user specific auth params of the Trello API to add to the post part.
     *
     * @return void
     */
    public function getAuthParams()
    {
        if (!$this->integration || !$this->integration->getIntegrationSettings()->getIsPublished()) {
            throw new Exception('Trello Plugin not published, or no integration provided');
        }
        $settings = $this->integration->getIntegrationSettings()->getFeatureSettings();

        return [
            'key' => $settings['appkey'],
            'token' => $settings['apitoken'],
        ];
    }

    /**
     * All the business logic for a submitted form.
     *
     * @return bool
     */
    public function addNewCard(array $card): Card
    {
        $api = $this->getApi();

        try {
            $card = $api->addCard($card);
            $this->logger->debug('Successfully added card to Trello', [$card->getIdList(), $card->getId(), $card->getName()]);

            return $card;
        } catch (InvalidArgumentException $e) {
            $this->logger->warning($e->getMessage(), $e->getTrace());
            $error = new Error();
            $error->setCode('InvalidArgument');
            $error->setMessage($e->getMessage());

            return new Exception($error);
        } catch (Exception $e) {
            $this->logger->error($e->getMessage(), $e->getTrace());

            return new Exception($e);
        }

        // return $this->redirectToRoute('task_success');
    }
}
