<?php

declare(strict_types=1);

namespace MauticPlugin\AivieTrelloBundle\Service;

use GuzzleHttp\Client as HttpClient;
use Mautic\CoreBundle\Helper\CoreParametersHelper;
use Mautic\UserBundle\Entity\User;
use MauticPlugin\AivieTrelloBundle\Integration\Config;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Api\DefaultApi;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\ApiException;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Configuration;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Model\Card;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Model\CardError;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Model\Member;
use MauticPlugin\AivieTrelloBundle\Openapi\lib\Model\NewCard;
use Psr\Log\LoggerInterface;

/**
 * Provide the auto generated Trello API to the AivieTrelloBundle.
 */
class TrelloApiService
{
    public function __construct(private CoreParametersHelper $coreParametersHelper, private LoggerInterface $logger, private Config $config)
    {
    }

    /**
     * Return the Api to Trello. Which is autogenerated from an OpenAPI specificaton.
     */
    public function getApi(): DefaultApi|bool
    {
        // setup auth
        $auth = $this->getAuthParams();
        if (!$this->config->isPublished() && !$this->config->isConfigured()) {
            return false;
        }

        Configuration::getDefaultConfiguration()->setApiKey('key', $auth['key']);
        $config = Configuration::getDefaultConfiguration()->setApiKey('token', $auth['token']);

        return new DefaultApi(
            new HttpClient(),
            $config
        );
    }

    /**
     * Get all Trello boards as an array (id => name).
     *
     * @return array<string, string>
     */
    public function getBoardsArray(string $filter = 'open'): array
    {
        try {
            $api = $this->getApi();
            if (!$api) {
                return [];
            }

            $fields      = 'id,name';
            $boards      = $api->getBoards($fields, $filter);
            $boardsArray = [];
            foreach ($boards as $board) {
                $boardsArray[$board->getId()] = $board->getName();
            }

            return $boardsArray;
        } catch (ApiException $e) {
            $this->logger->warning('API Exception when calling DefaultApi->getBoards(): ', [$e->getMessage()]);

            return [];
        }
    }

    /**
     * Get the users favourite board from Settings.
     */
    public function getFavouriteBoard(): string
    {
        return $this->coreParametersHelper->get('favorite_board', '') ?? '';
    }

    /**
     * Get all the lists on the Trello board.
     *
     * @param int|null $boardId Trello Board id
     *
     * @return array<int, mixed>
     */
    public function getListsOnBoard(?int $boardId = null): array
    {
        $api = $this->getApi();
        if (!$api) {
            return [];
        }

        if (empty($boardId)) {
            $boardId = $this->getFavouriteBoard();
            if (empty($boardId)) {
                $this->logger->warning('no board configured');

                return [];
            }
        }

        try {
            return $api->getLists($boardId);
        } catch (ApiException $e) {
            $this->logger->warning('API Exception when calling DefaultApi->getLists(): ', [$e->getMessage()]);

            return [];
        } catch (\Exception $e) {
            $this->logger->warning('Exception when calling DefaultApi->getLists(): ', [$e->getMessage()]);

            return [];
        }
    }

    /**
     * Get the user specific auth params of the Trello API to add to the post part.
     *
     * @return array<string, string> the auth params as an array
     */
    public function getAuthParams(): array
    {
        if (!$this->config->isPublished() && !$this->config->isConfigured()) {
            return [];
        }

        $keys = $this->config->getApiKeys();

        if (empty($keys['appkey']) || empty($keys['apitoken'])) {
            $this->logger->warning('No valid Trello api keys');
        }

        return [
            'key'   => isset($keys['appkey']) ? $keys['appkey'] : '',
            'token' => isset($keys['apitoken']) ? $keys['apitoken'] : '',
        ];
    }

    /**
     * All the business logic for a submitted form.
     *
     * @param array<string, mixed> $card
     */
    public function addNewCard(array $card): Card|\Exception|CardError
    {
        $api = $this->getApi();
        if (!$api) {
            return new Card();
        }

        try {
            $card = $api->addCard(new NewCard($card));
            if ($card instanceof Card) {
                $this->logger->debug('Successfully added card to Trello', [$card->getIdList(), $card->getId(), $card->getName()]);
            }

            return $card;
        } catch (\InvalidArgumentException $e) {
            $this->logger->warning($e->getMessage(), $e->getTrace());

            return new \Exception('InvalidArgument: '.$e->getMessage());
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage(), $e->getTrace());

            return new \Exception($e->getMessage());
        }

        // return $this->redirectToRoute('task_success');
    }

    /**
     * Find the card on the given board that has an attachment URL matching the lead (contact).
     * Attachment URL is expected to be the full site URL plus /s/contacts/view/{leadId}.
     */
    public function findCardForLead(string $boardId, int $leadId): ?Card
    {
        $api = $this->getApi();
        if (!$api instanceof DefaultApi) {
            $this->logger->warning('Trello: No API found for board', ['boardId' => $boardId]);

            return null;
        }

        $cards = $api->getCardsOnBoard($boardId);

        if (!is_array($cards)) {
            $this->logger->warning('Trello: No cards found on board', ['boardId' => $boardId]);

            return null;
        }

        $siteUrl     = rtrim((string) $this->coreParametersHelper->get('site_url', ''), '/');
        $expectedUrl = $siteUrl.'/s/contacts/view/'.$leadId;

        // sort the cards by dateLastActivity descending
        usort($cards, function ($a, $b) {
            return $b->getDateLastActivity() <=> $a->getDateLastActivity();
        });
        foreach ($cards as $card) {
            $attachments = $card->getAttachments();

            if (!is_array($attachments)) {
                continue;
            }
            foreach ($attachments as $attachment) {
                if (isset($attachment['url']) && $attachment['url'] === $expectedUrl) {
                    return $card;
                }
            }
        }

        return null;
    }

    /**
     * Ensure the card has a checklist (create "Todo" if none), then add the check item.
     */
    public function addChecklistItemToCard(Card $card, string $itemName): void
    {
        $api = $this->getApi();
        if (!$api instanceof DefaultApi) {
            return;
        }

        $checklistIds = $card->getIdChecklists();
        if (empty($checklistIds) || empty($checklistIds[0])) {
            $api->addChecklistOnCard($card->getId(), 'Todo');
            $card         = $api->getCard($card->getId());
            $checklistIds = $card->getIdChecklists();
            $this->logger->debug('Trello: Checklist added to card: Todo', ['cardId' => $card->getId(), 'checklistIds' => $checklistIds]);
        }

        $checklistId = $checklistIds[0];
        $api->addChecklistItemOnCard($checklistId, $itemName);
        $this->logger->debug('Trello: Checklist item added to card', ['cardId' => $card->getId(), 'checklistId' => $checklistId, 'itemName' => $itemName]);
    }

    /**
     * Update only the due date of a card. Returns the updated card or null on failure.
     * Set the idMembers if you also want to change the assignees of the card.
     *
     * @param array<int, string>|null $idMembers
     */
    public function updateCardDueDate(string $cardId, ?string $dueDate, ?array $idMembers): ?Card
    {
        $api = $this->getApi();
        if (!$api instanceof DefaultApi) {
            return null;
        }

        try {
            $due = null;
            if (!empty($dueDate)) {
                $due = new \DateTime($dueDate);
            }

            $card = $api->updateCard($cardId, null, null, null, null, null, null, $due, null, null, null, null === $idMembers ? null : implode(',', $idMembers));

            return $card instanceof Card ? $card : null;
        } catch (\Throwable $e) {
            $this->logger->warning('Trello: updateCard due date failed', ['cardId' => $cardId, 'message' => $e->getMessage()]);

            return null;
        }
    }

    public function getBoardMemberForUser(string $boardId, User $user): ?Member
    {
        $api = $this->getApi();
        if (!$api instanceof DefaultApi) {
            return null;
        }

        try {
            $members = $api->getBoardMembers($boardId);
            if (!is_array($members)) {
                return null;
            }

            foreach ($members as $member) {
                $member = $api->getMember($member->getId());
                if (!$member instanceof Member) {
                    continue;
                }
                if ($member->getEmail() === $user->getEmail()) {
                    return $member;
                }
            }

            return null;
        } catch (\Exception $e) {
            $this->logger->warning('Exception when calling DefaultApi->getBoardMembers(): ', [$e->getMessage()]);

            return null;
        }
    }
}
