<?php
/**
 * Card
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MauticPlugin\MauticTrelloBundle\Openapi\lib
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mautic Trello API
 *
 * Create or update a card via the Trello API
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MauticPlugin\MauticTrelloBundle\Openapi\lib\Model;

use ArrayAccess;
use MauticPlugin\MauticTrelloBundle\Openapi\lib\ObjectSerializer;

/**
 * Card Class Doc Comment
 *
 * @category Class
 * @package  MauticPlugin\MauticTrelloBundle\Openapi\lib
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Card implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Card';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'idList' => 'string',
        'desc' => 'string',
        'pos' => 'string',
        'due' => '\DateTime',
        'contactId' => 'int',
        'keepFromSource' => 'string',
        'id' => 'string',
        'dateLastActivity' => '\DateTime',
        'labels' => 'object[]',
        'url' => 'string',
        'idMembers' => 'string[]',
        'attachments' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'idList' => null,
        'desc' => null,
        'pos' => null,
        'due' => 'date-time',
        'contactId' => null,
        'keepFromSource' => null,
        'id' => null,
        'dateLastActivity' => 'date-time',
        'labels' => null,
        'url' => 'uri',
        'idMembers' => null,
        'attachments' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'idList' => false,
        'desc' => false,
        'pos' => false,
        'due' => false,
        'contactId' => false,
        'keepFromSource' => false,
        'id' => false,
        'dateLastActivity' => false,
        'labels' => false,
        'url' => false,
        'idMembers' => false,
        'attachments' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'idList' => 'idList',
        'desc' => 'desc',
        'pos' => 'pos',
        'due' => 'due',
        'contactId' => 'contactId',
        'keepFromSource' => 'keepFromSource',
        'id' => 'id',
        'dateLastActivity' => 'dateLastActivity',
        'labels' => 'labels',
        'url' => 'url',
        'idMembers' => 'idMembers',
        'attachments' => 'attachments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'idList' => 'setIdList',
        'desc' => 'setDesc',
        'pos' => 'setPos',
        'due' => 'setDue',
        'contactId' => 'setContactId',
        'keepFromSource' => 'setKeepFromSource',
        'id' => 'setId',
        'dateLastActivity' => 'setDateLastActivity',
        'labels' => 'setLabels',
        'url' => 'setUrl',
        'idMembers' => 'setIdMembers',
        'attachments' => 'setAttachments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'idList' => 'getIdList',
        'desc' => 'getDesc',
        'pos' => 'getPos',
        'due' => 'getDue',
        'contactId' => 'getContactId',
        'keepFromSource' => 'getKeepFromSource',
        'id' => 'getId',
        'dateLastActivity' => 'getDateLastActivity',
        'labels' => 'getLabels',
        'url' => 'getUrl',
        'idMembers' => 'getIdMembers',
        'attachments' => 'getAttachments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('idList', $data ?? [], null);
        $this->setIfExists('desc', $data ?? [], null);
        $this->setIfExists('pos', $data ?? [], null);
        $this->setIfExists('due', $data ?? [], null);
        $this->setIfExists('contactId', $data ?? [], null);
        $this->setIfExists('keepFromSource', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('dateLastActivity', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('idMembers', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['idList'] === null) {
            $invalidProperties[] = "'idList' can't be null";
        }
        if ((mb_strlen($this->container['idList']) < 1)) {
            $invalidProperties[] = "invalid value for 'idList', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['contactId']) && ($this->container['contactId'] < 0)) {
            $invalidProperties[] = "invalid value for 'contactId', must be bigger than or equal to 0.";
        }

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Card Name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Card., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets idList
     *
     * @return string
     */
    public function getIdList()
    {
        return $this->container['idList'];
    }

    /**
     * Sets idList
     *
     * @param string $idList The ID of the list the card should be created in
     *
     * @return self
     */
    public function setIdList($idList)
    {
        if (is_null($idList)) {
            throw new \InvalidArgumentException('non-nullable idList cannot be null');
        }

        if ((mb_strlen($idList) < 1)) {
            throw new \InvalidArgumentException('invalid length for $idList when calling Card., must be bigger than or equal to 1.');
        }

        $this->container['idList'] = $idList;

        return $this;
    }

    /**
     * Gets desc
     *
     * @return string|null
     */
    public function getDesc()
    {
        return $this->container['desc'];
    }

    /**
     * Sets desc
     *
     * @param string|null $desc Card Description
     *
     * @return self
     */
    public function setDesc($desc)
    {
        if (is_null($desc)) {
            throw new \InvalidArgumentException('non-nullable desc cannot be null');
        }
        $this->container['desc'] = $desc;

        return $this;
    }

    /**
     * Gets pos
     *
     * @return string|null
     */
    public function getPos()
    {
        return $this->container['pos'];
    }

    /**
     * Sets pos
     *
     * @param string|null $pos pos
     *
     * @return self
     */
    public function setPos($pos)
    {
        if (is_null($pos)) {
            throw new \InvalidArgumentException('non-nullable pos cannot be null');
        }
        $this->container['pos'] = $pos;

        return $this;
    }

    /**
     * Gets due
     *
     * @return \DateTime|null
     */
    public function getDue()
    {
        return $this->container['due'];
    }

    /**
     * Sets due
     *
     * @param \DateTime|null $due full-date notation as defined by RFC 3339, section 5.6. Default Timezone is UTC
     *
     * @return self
     */
    public function setDue($due)
    {
        if (is_null($due)) {
            throw new \InvalidArgumentException('non-nullable due cannot be null');
        }
        $this->container['due'] = $due;

        return $this;
    }

    /**
     * Gets contactId
     *
     * @return int|null
     */
    public function getContactId()
    {
        return $this->container['contactId'];
    }

    /**
     * Sets contactId
     *
     * @param int|null $contactId The ID of the Mautic contact (Lead).
     *
     * @return self
     */
    public function setContactId($contactId)
    {
        if (is_null($contactId)) {
            throw new \InvalidArgumentException('non-nullable contactId cannot be null');
        }

        if (($contactId < 0)) {
            throw new \InvalidArgumentException('invalid value for $contactId when calling Card., must be bigger than or equal to 0.');
        }

        $this->container['contactId'] = $contactId;

        return $this;
    }

    /**
     * Gets keepFromSource
     *
     * @return string|null
     */
    public function getKeepFromSource()
    {
        return $this->container['keepFromSource'];
    }

    /**
     * Sets keepFromSource
     *
     * @param string|null $keepFromSource If using idCardSource you can specify which properties to copy over.
     *
     * @return self
     */
    public function setKeepFromSource($keepFromSource)
    {
        if (is_null($keepFromSource)) {
            throw new \InvalidArgumentException('non-nullable keepFromSource cannot be null');
        }
        $this->container['keepFromSource'] = $keepFromSource;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling Card., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets dateLastActivity
     *
     * @return \DateTime|null
     */
    public function getDateLastActivity()
    {
        return $this->container['dateLastActivity'];
    }

    /**
     * Sets dateLastActivity
     *
     * @param \DateTime|null $dateLastActivity full-date notation as defined by RFC 3339, section 5.6. Default Timezone is UTC
     *
     * @return self
     */
    public function setDateLastActivity($dateLastActivity)
    {
        if (is_null($dateLastActivity)) {
            throw new \InvalidArgumentException('non-nullable dateLastActivity cannot be null');
        }
        $this->container['dateLastActivity'] = $dateLastActivity;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return object[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param object[]|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url to the Trello card
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets idMembers
     *
     * @return string[]|null
     */
    public function getIdMembers()
    {
        return $this->container['idMembers'];
    }

    /**
     * Sets idMembers
     *
     * @param string[]|null $idMembers Array of memebr ids as strings
     *
     * @return self
     */
    public function setIdMembers($idMembers)
    {
        if (is_null($idMembers)) {
            throw new \InvalidArgumentException('non-nullable idMembers cannot be null');
        }
        $this->container['idMembers'] = $idMembers;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return object[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param object[]|null $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
