<?php
/**
 * CardAllOfTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * CardAllOfTest Class Doc Comment.
 *
 * @category    Class */
// * @description CardAllOf
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class CardAllOfTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CardAllOf".
     */
    public function testCardAllOf()
    {
        $testCardAllOf = new CardAllOf();
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "labels".
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "url".
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "dateLastActivity".
     */
    public function testPropertyDateLastActivity()
    {
    }

    /**
     * Test attribute "due".
     */
    public function testPropertyDue()
    {
    }

    /**
     * Test attribute "idMembers".
     */
    public function testPropertyIdMembers()
    {
    }

    /**
     * Test attribute "attachments".
     */
    public function testPropertyAttachments()
    {
    }
}
