<?php
/**
 * CardErrorTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * CardErrorTest Class Doc Comment.
 *
 * @category    Class */
// * @description CardError
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class CardErrorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CardError".
     */
    public function testCardError()
    {
        $testCardError = new CardError();
    }

    /**
     * Test attribute "code".
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "message".
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "data".
     */
    public function testPropertyData()
    {
    }
}
