<?php
/**
 * InlineResponse200Test.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * InlineResponse200Test Class Doc Comment.
 *
 * @category    Class */
// * @description InlineResponse200
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class InlineResponse200Test extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "InlineResponse200".
     */
    public function testInlineResponse200()
    {
        $testInlineResponse200 = new InlineResponse200();
    }

    /**
     * Test attribute "card".
     */
    public function testPropertyCard()
    {
    }
}
