<?php
/**
 * NewCardTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * NewCardTest Class Doc Comment.
 *
 * @category    Class */
// * @description NewCard
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class NewCardTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "NewCard".
     */
    public function testNewCard()
    {
        $testNewCard = new NewCard();
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "idList".
     */
    public function testPropertyIdList()
    {
    }

    /**
     * Test attribute "desc".
     */
    public function testPropertyDesc()
    {
    }

    /**
     * Test attribute "pos".
     */
    public function testPropertyPos()
    {
    }

    /**
     * Test attribute "due".
     */
    public function testPropertyDue()
    {
    }

    /**
     * Test attribute "urlSource".
     */
    public function testPropertyUrlSource()
    {
    }

    /**
     * Test attribute "keepFromSource".
     */
    public function testPropertyKeepFromSource()
    {
    }
}
