<?php
/**
 * CardError.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the CardError model.
 *
 * @author  OpenAPI Generator team
 */
class CardError
{
    /**
     * short error code.
     *
     * @var string
     * @SerializedName("code")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $code;

    /**
     * plain text error message for displaying to user.
     *
     * @var string
     * @SerializedName("message")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $message;

    /**
     * @var MauticPlugin\Idea2TrelloBundle\Openapi\Model\CardErrorData|null
     * @SerializedName("data")
     * @Assert\Type("MauticPlugin\Idea2TrelloBundle\Openapi\Model\CardErrorData")
     * @Type("MauticPlugin\Idea2TrelloBundle\Openapi\Model\CardErrorData")
     */
    protected $data;

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->code = isset($data['code']) ? $data['code'] : null;
        $this->message = isset($data['message']) ? $data['message'] : null;
        $this->data = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * Gets code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Sets code.
     *
     * @param string $code short error code
     *
     * @return $this
     */
    public function setCode(string $code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Gets message.
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Sets message.
     *
     * @param string $message plain text error message for displaying to user
     *
     * @return $this
     */
    public function setMessage(string $message)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Gets data.
     *
     * @return MauticPlugin\Idea2TrelloBundle\Openapi\Model\CardErrorData|null
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Sets data.
     *
     * @param MauticPlugin\Idea2TrelloBundle\Openapi\Model\CardErrorData|null $data
     *
     * @return $this
     */
    public function setData(CardErrorData $data = null)
    {
        $this->data = $data;

        return $this;
    }
}
