<?php
/**
 * InlineResponse200.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Idea2 Trello API.
 *
 * Create card in Trello
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace MauticPlugin\Idea2TrelloBundle\Openapi\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the InlineResponse200 model.
 *
 * @author  OpenAPI Generator team
 */
class InlineResponse200
{
    /**
     * @var MauticPlugin\Idea2TrelloBundle\Openapi\Model\Card|null
     * @SerializedName("card")
     * @Assert\Type("MauticPlugin\Idea2TrelloBundle\Openapi\Model\Card")
     * @Type("MauticPlugin\Idea2TrelloBundle\Openapi\Model\Card")
     */
    protected $card;

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->card = isset($data['card']) ? $data['card'] : null;
    }

    /**
     * Gets card.
     *
     * @return MauticPlugin\Idea2TrelloBundle\Openapi\Model\Card|null
     */
    public function getCard()
    {
        return $this->card;
    }

    /**
     * Sets card.
     *
     * @param MauticPlugin\Idea2TrelloBundle\Openapi\Model\Card|null $card
     *
     * @return $this
     */
    public function setCard(Card $card = null)
    {
        $this->card = $card;

        return $this;
    }
}
